"use client";
import { useState } from "react";
import type { XReading } from "@/lib/types";

const fmt = (n: number) => `₱${n.toFixed(2)}`;

const mockXReading: XReading = {
  id: "xr-001",
  reportDate: "2026-04-25",
  reportTime: "14:30:00",
  machineSerial: "SN-2024-001",
  beginningOrNumber: 49800,
  lastOrNumber: 49920,
  grossSales: 125750.0,
  vatableSales: 112276.79,
  vatExemptSales: 8500.0,
  vatAmount: 13473.21,
  zeroRatedSales: 0,
  scDiscount: 2500.0,
  pwdDiscount: 1200.0,
  promotionalDiscount: 800.0,
  totalDiscounts: 4500.0,
  totalVoids: 3,
  voidAmount: 1250.0,
  totalReturns: 1,
  returnAmount: 450.0,
  netSales: 119550.0,
  generatedBy: "Maria Santos",
  generatedAt: "2026-04-25T14:30:00",
};

export function XReadingReport() {
  const [generated, setGenerated] = useState(false);
  const r = mockXReading;

  return (
    <div>
      <div className="report-actions">
        <button
          className="primary report-generate-btn"
          onClick={() => setGenerated(true)}
          disabled={generated}
        >
          {generated ? "✓ X-Reading Generated" : "Generate X-Reading"}
        </button>
        <span className="report-permission-note">(Cashier and above)</span>
      </div>

      {generated && (
        <div className="bir-report-card">
          <div className="bir-report-header">
            <h2>X-READING REPORT</h2>
            <p>
              Date: {r.reportDate} &nbsp;|&nbsp; Time: {r.reportTime}
            </p>
            <p>Machine S/N: {r.machineSerial}</p>
          </div>

          <div className="bir-report-section">
            <div className="bir-report-row">
              <span className="label">Beginning OR#</span>
              <span className="value">{r.beginningOrNumber}</span>
            </div>
            <div className="bir-report-row">
              <span className="label">Last OR# Issued</span>
              <span className="value">{r.lastOrNumber}</span>
            </div>
          </div>

          <div className="bir-report-section">
            <div className="bir-report-row">
              <span className="label">Gross Sales</span>
              <span className="value">{fmt(r.grossSales)}</span>
            </div>
            <div className="bir-report-row">
              <span className="label">VATable Sales</span>
              <span className="value">{fmt(r.vatableSales)}</span>
            </div>
            <div className="bir-report-row">
              <span className="label">VAT-Exempt Sales</span>
              <span className="value">{fmt(r.vatExemptSales)}</span>
            </div>
            <div className="bir-report-row">
              <span className="label">VAT Amount</span>
              <span className="value">{fmt(r.vatAmount)}</span>
            </div>
            <div className="bir-report-row">
              <span className="label">Zero-Rated Sales</span>
              <span className="value">{fmt(r.zeroRatedSales)}</span>
            </div>
          </div>

          <div className="bir-report-section">
            <div className="bir-report-row">
              <span className="label">SC Discount</span>
              <span className="value">{fmt(r.scDiscount)}</span>
            </div>
            <div className="bir-report-row">
              <span className="label">PWD Discount</span>
              <span className="value">{fmt(r.pwdDiscount)}</span>
            </div>
            <div className="bir-report-row">
              <span className="label">Promotional Discount</span>
              <span className="value">{fmt(r.promotionalDiscount)}</span>
            </div>
            <div className="bir-report-row">
              <span className="label">Total Discounts</span>
              <span className="value">{fmt(r.totalDiscounts)}</span>
            </div>
          </div>

          <div className="bir-report-section">
            <div className="bir-report-row">
              <span className="label">Total Voids ({r.totalVoids})</span>
              <span className="value">{fmt(r.voidAmount)}</span>
            </div>
            <div className="bir-report-row">
              <span className="label">Total Returns ({r.totalReturns})</span>
              <span className="value">{fmt(r.returnAmount)}</span>
            </div>
          </div>

          <div className="bir-report-section">
            <div className="bir-report-row total">
              <span className="label">Net Sales</span>
              <span className="value">{fmt(r.netSales)}</span>
            </div>
          </div>

          <div className="bir-report-row">
            <span className="label">Generated By</span>
            <span className="value">{r.generatedBy}</span>
          </div>
          <div className="bir-report-row">
            <span className="label">Timestamp</span>
            <span className="value">{r.generatedAt}</span>
          </div>

          <div className="report-actions" style={{ marginTop: 16 }}>
            <button className="primary">🖨️ Print X-Reading</button>
          </div>
        </div>
      )}
    </div>
  );
}
